--Export by excel config file, don't modify this file!
--[[
ID(Column[A] Type[int] Desc[房间编号]
Type(Column[C] Type[int] Desc[房间模式]
Level(Column[D] Type[int] Desc[房间等级]
Name(Column[E] Type[string] Desc[房间名称]
IsOpen(Column[F] Type[int] Desc[是否开启]
LowLimit(Column[G] Type[int] Desc[台面底注]
HighLimit(Column[H] Type[int] Desc[投注上限]
EnterLimit(Column[I] Type[int] Desc[准入下限金币]
OutLimit(Column[J] Type[int] Desc[准入上限金币]
]]--

data.PublicroomConfig =
{
    [1] =
    {
        ID = 1,
        Type = 1,
        Level = 1,
        Name = "平民场",
        IsOpen = 1,
        LowLimit = 1,
        HighLimit = 40,
        EnterLimit = 50,
        OutLimit = 2000,
    },
    [2] =
    {
        ID = 2,
        Type = 1,
        Level = 2,
        Name = "小资场",
        IsOpen = 1,
        LowLimit = 5,
        HighLimit = 200,
        EnterLimit = 250,
        OutLimit = 10000,
    },
    [3] =
    {
        ID = 3,
        Type = 1,
        Level = 3,
        Name = "老板场",
        IsOpen = 1,
        LowLimit = 10,
        HighLimit = 400,
        EnterLimit = 500,
        OutLimit = 20000,
    },
    [4] =
    {
        ID = 4,
        Type = 1,
        Level = 4,
        Name = "土豪场",
        IsOpen = 1,
        LowLimit = 20,
        HighLimit = 800,
        EnterLimit = 1000,
        OutLimit = 4500000,
    },
    [5] =
    {
        ID = 5,
        Type = 1,
        Level = 5,
        Name = "贵族场",
        IsOpen = 1,
        LowLimit = 50,
        HighLimit = 2000,
        EnterLimit = 2500,
        OutLimit = 99999999,
    },
    [6] =
    {
        ID = 6,
        Type = 1,
        Level = 6,
        Name = "皇家场",
        IsOpen = 1,
        LowLimit = 100,
        HighLimit = 4000,
        EnterLimit = 5000,
        OutLimit = 99999999,
    },
    [7] =
    {
        ID = 7,
        Type = 2,
        Level = 1,
        Name = "平民场",
        IsOpen = 1,
        LowLimit = 100,
        HighLimit = 4000,
        EnterLimit = 4000,
        OutLimit = 2000,
    },
    [8] =
    {
        ID = 8,
        Type = 2,
        Level = 2,
        Name = "小资场",
        IsOpen = 1,
        LowLimit = 200,
        HighLimit = 8000,
        EnterLimit = 8000,
        OutLimit = 4000,
    },
    [9] =
    {
        ID = 9,
        Type = 2,
        Level = 3,
        Name = "老板场",
        IsOpen = 1,
        LowLimit = 1000,
        HighLimit = 40000,
        EnterLimit = 40000,
        OutLimit = 20000,
    },
    [10] =
    {
        ID = 10,
        Type = 2,
        Level = 4,
        Name = "土豪场",
        IsOpen = 1,
        LowLimit = 2000,
        HighLimit = 80000,
        EnterLimit = 80000,
        OutLimit = 40000,
    },
    [11] =
    {
        ID = 11,
        Type = 2,
        Level = 5,
        Name = "贵族场",
        IsOpen = 1,
        LowLimit = 5000,
        HighLimit = 200000,
        EnterLimit = 200000,
        OutLimit = 100000,
    },
    [12] =
    {
        ID = 12,
        Type = 2,
        Level = 6,
        Name = "皇家场",
        IsOpen = 1,
        LowLimit = 10000,
        HighLimit = 400000,
        EnterLimit = 400000,
        OutLimit = 200000,
    },
    [13] =
    {
        ID = 13,
        Type = 3,
        Level = 1,
        Name = "平民场",
        IsOpen = 1,
        LowLimit = 10,
        HighLimit = 0,
        EnterLimit = 2000,
        OutLimit = 500,
    },
    [14] =
    {
        ID = 14,
        Type = 3,
        Level = 2,
        Name = "小资场",
        IsOpen = 1,
        LowLimit = 20,
        HighLimit = 0,
        EnterLimit = 4000,
        OutLimit = 1000,
    },
    [15] =
    {
        ID = 15,
        Type = 3,
        Level = 3,
        Name = "老板场",
        IsOpen = 1,
        LowLimit = 100,
        HighLimit = 0,
        EnterLimit = 20000,
        OutLimit = 5000,
    },
    [16] =
    {
        ID = 16,
        Type = 3,
        Level = 4,
        Name = "土豪场",
        IsOpen = 1,
        LowLimit = 200,
        HighLimit = 0,
        EnterLimit = 40000,
        OutLimit = 10000,
    },
    [17] =
    {
        ID = 17,
        Type = 3,
        Level = 5,
        Name = "贵族场",
        IsOpen = 1,
        LowLimit = 500,
        HighLimit = 0,
        EnterLimit = 100000,
        OutLimit = 20000,
    },
    [18] =
    {
        ID = 18,
        Type = 3,
        Level = 6,
        Name = "皇家场",
        IsOpen = 1,
        LowLimit = 1000,
        HighLimit = 0,
        EnterLimit = 200000,
        OutLimit = 50000,
    },
    [19] =
    {
        ID = 19,
        Type = 4,
        Level = 1,
        Name = "平民场",
        IsOpen = 1,
        LowLimit = 1,
        HighLimit = 0,
        EnterLimit = 50,
        OutLimit = 2000,
    },
    [20] =
    {
        ID = 20,
        Type = 4,
        Level = 2,
        Name = "小资场",
        IsOpen = 1,
        LowLimit = 5,
        HighLimit = 0,
        EnterLimit = 250,
        OutLimit = 10000,
    },
    [21] =
    {
        ID = 21,
        Type = 4,
        Level = 3,
        Name = "老板场",
        IsOpen = 1,
        LowLimit = 10,
        HighLimit = 0,
        EnterLimit = 500,
        OutLimit = 20000,
    },
    [22] =
    {
        ID = 22,
        Type = 4,
        Level = 4,
        Name = "土豪场",
        IsOpen = 1,
        LowLimit = 20,
        HighLimit = 0,
        EnterLimit = 1000,
        OutLimit = 4500000,
    },
    [23] =
    {
        ID = 23,
        Type = 4,
        Level = 5,
        Name = "贵族场",
        IsOpen = 1,
        LowLimit = 50,
        HighLimit = 0,
        EnterLimit = 3000,
        OutLimit = 99999999,
    },
    [24] =
    {
        ID = 24,
        Type = 4,
        Level = 6,
        Name = "皇家场",
        IsOpen = 1,
        LowLimit = 100,
        HighLimit = 0,
        EnterLimit = 5000,
        OutLimit = 99999999,
    },
    [25] =
    {
        ID = 25,
        Type = 8,
        Level = 1,
        Name = "平民场",
        IsOpen = 1,
        LowLimit = 10,
        HighLimit = 0,
        EnterLimit = 2000,
        OutLimit = 500,
    },
    [26] =
    {
        ID = 26,
        Type = 8,
        Level = 2,
        Name = "小资场",
        IsOpen = 1,
        LowLimit = 20,
        HighLimit = 0,
        EnterLimit = 4000,
        OutLimit = 1000,
    },
    [27] =
    {
        ID = 27,
        Type = 8,
        Level = 3,
        Name = "老板场",
        IsOpen = 1,
        LowLimit = 100,
        HighLimit = 0,
        EnterLimit = 20000,
        OutLimit = 5000,
    },
    [28] =
    {
        ID = 28,
        Type = 8,
        Level = 4,
        Name = "土豪场",
        IsOpen = 1,
        LowLimit = 200,
        HighLimit = 0,
        EnterLimit = 40000,
        OutLimit = 10000,
    },
    [29] =
    {
        ID = 29,
        Type = 8,
        Level = 5,
        Name = "贵族场",
        IsOpen = 1,
        LowLimit = 500,
        HighLimit = 0,
        EnterLimit = 100000,
        OutLimit = 20000,
    },
    [30] =
    {
        ID = 30,
        Type = 8,
        Level = 6,
        Name = "皇家场",
        IsOpen = 1,
        LowLimit = 1000,
        HighLimit = 0,
        EnterLimit = 200000,
        OutLimit = 50000,
    },
    [31] =
    {
        ID = 31,
        Type = 9,
        Level = 1,
        Name = "平民场",
        IsOpen = 1,
        LowLimit = 1,
        HighLimit = 0,
        EnterLimit = 50,
        OutLimit = 2000,
    },
    [32] =
    {
        ID = 32,
        Type = 9,
        Level = 2,
        Name = "小资场",
        IsOpen = 1,
        LowLimit = 5,
        HighLimit = 0,
        EnterLimit = 250,
        OutLimit = 10000,
    },
    [33] =
    {
        ID = 33,
        Type = 9,
        Level = 3,
        Name = "老板场",
        IsOpen = 1,
        LowLimit = 10,
        HighLimit = 0,
        EnterLimit = 500,
        OutLimit = 4500000,
    },
    [34] =
    {
        ID = 34,
        Type = 9,
        Level = 4,
        Name = "土豪场",
        IsOpen = 1,
        LowLimit = 20,
        HighLimit = 0,
        EnterLimit = 1000,
        OutLimit = 4500000,
    },
    [35] =
    {
        ID = 35,
        Type = 9,
        Level = 5,
        Name = "贵族场",
        IsOpen = 0,
        LowLimit = 50,
        HighLimit = 0,
        EnterLimit = 3000,
        OutLimit = 99999999,
    },
    [36] =
    {
        ID = 36,
        Type = 9,
        Level = 6,
        Name = "皇家场",
        IsOpen = 0,
        LowLimit = 100,
        HighLimit = 0,
        EnterLimit = 5000,
        OutLimit = 99999999,
    },
    [37] =
    {
        ID = 37,
        Type = 10,
        Level = 1,
        Name = "平民场",
        IsOpen = 1,
        LowLimit = 100,
        HighLimit = 0,
        EnterLimit = 4000,
        OutLimit = 2000,
    },
    [38] =
    {
        ID = 38,
        Type = 10,
        Level = 2,
        Name = "小资场",
        IsOpen = 1,
        LowLimit = 200,
        HighLimit = 0,
        EnterLimit = 8000,
        OutLimit = 4000,
    },
    [39] =
    {
        ID = 39,
        Type = 10,
        Level = 3,
        Name = "老板场",
        IsOpen = 1,
        LowLimit = 1000,
        HighLimit = 0,
        EnterLimit = 40000,
        OutLimit = 20000,
    },
    [40] =
    {
        ID = 40,
        Type = 10,
        Level = 4,
        Name = "土豪场",
        IsOpen = 1,
        LowLimit = 2000,
        HighLimit = 0,
        EnterLimit = 80000,
        OutLimit = 40000,
    },
    [41] =
    {
        ID = 41,
        Type = 10,
        Level = 5,
        Name = "贵族场",
        IsOpen = 1,
        LowLimit = 4000,
        HighLimit = 0,
        EnterLimit = 160000,
        OutLimit = 80000,
    },
    [42] =
    {
        ID = 42,
        Type = 10,
        Level = 6,
        Name = "皇家场",
        IsOpen = 1,
        LowLimit = 10000,
        HighLimit = 0,
        EnterLimit = 400000,
        OutLimit = 200000,
    },
    [43] =
    {
        ID = 43,
        Type = 11,
        Level = 1,
        Name = "平民场",
        IsOpen = 1,
        LowLimit = 0.01,
        HighLimit = 0,
        EnterLimit = 1,
        OutLimit = 10,
    },
    [44] =
    {
        ID = 44,
        Type = 11,
        Level = 2,
        Name = "小资场",
        IsOpen = 1,
        LowLimit = 0.1,
        HighLimit = 0,
        EnterLimit = 10,
        OutLimit = 200,
    },
    [45] =
    {
        ID = 45,
        Type = 11,
        Level = 3,
        Name = "老板场",
        IsOpen = 1,
        LowLimit = 1,
        HighLimit = 0,
        EnterLimit = 100,
        OutLimit = 1000,
    },
    [46] =
    {
        ID = 46,
        Type = 11,
        Level = 4,
        Name = "土豪场",
        IsOpen = 1,
        LowLimit = 5,
        HighLimit = 0,
        EnterLimit = 500,
        OutLimit = 4500000,
    },
    [47] =
    {
        ID = 47,
        Type = 11,
        Level = 5,
        Name = "贵族场",
        IsOpen = 0,
        LowLimit = 20,
        HighLimit = 0,
        EnterLimit = 2000,
        OutLimit = 99999999,
    },
    [48] =
    {
        ID = 48,
        Type = 11,
        Level = 6,
        Name = "皇家场",
        IsOpen = 0,
        LowLimit = 50,
        HighLimit = 0,
        EnterLimit = 5000,
        OutLimit = 99999999,
    },
    [49] =
    {
        ID = 49,
        Type = 12,
        Level = 1,
        Name = "初级场",
        IsOpen = 1,
        LowLimit = 0,
        HighLimit = 0,
        EnterLimit = 1,
        OutLimit = 99999999,
    },
    [50] =
    {
        ID = 50,
        Type = 12,
        Level = 2,
        Name = "高级场",
        IsOpen = 1,
        LowLimit = 0,
        HighLimit = 0,
        EnterLimit = 500,
        OutLimit = 99999999,
    },
    [51] =
    {
        ID = 51,
        Type = 13,
        Level = 1,
        Name = "初级场",
        IsOpen = 1,
        LowLimit = 2,
        HighLimit = 0,
        EnterLimit = 1,
        OutLimit = 4000,
    },
    [52] =
    {
        ID = 52,
        Type = 13,
        Level = 2,
        Name = "中级场",
        IsOpen = 1,
        LowLimit = 5,
        HighLimit = 0,
        EnterLimit = 50,
        OutLimit = 10000,
    },
    [53] =
    {
        ID = 53,
        Type = 13,
        Level = 3,
        Name = "高级场",
        IsOpen = 1,
        LowLimit = 10,
        HighLimit = 0,
        EnterLimit = 100,
        OutLimit = 4500000,
    },
}

