/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet
{

    public enum DefaultMessageIDTypes
    {
        /// <summary>
        /// 来自于一个连接的系统的Ping。更新时间戳(仅仅内部使用)
        /// </summary>
        ID_CONNECTED_PING,
        /// <summary>
        /// 来自于一个未连接系统的Ping。回复，但是不要更新时间戳(仅仅内部使用)
        /// </summary>
        ID_UNCONNECTED_PING,
        /// <summary>
        /// 来自于未连接系统的Ping，如果已经打开了连接，则回复，不要更新时间戳(仅用于内部)
        /// </summary>
        ID_UNCONNECTED_PING_OPEN_CONNECTIONS,
        /// <summary>
        /// 来自连接系统的Pong，更新时间戳(仅内部内部)
        /// </summary>
        ID_CONNECTED_PONG,
        /// <summary>
        /// 一个可靠数据包，用于检测连接丢失(仅仅用于内部)
        /// </summary>
        ID_DETECT_LOST_CONNECTIONS,
        /// <summary>
        /// S2C: Header(1), OfflineMesageID(16), server GUID(8), HasSecurity(1),
        /// Cookie(4, 如果设置了HasSecurity), public key (如果doSecurity设置为true),
        /// MTU(2). 如果公钥在客户端使用失败，返回:ID_PUBLIC_KEY_MISMATCH
        /// </summary>
        ID_OPEN_CONNECTION_REQUEST_1,
        /// <summary>
        /// S2C: Header(1), OfflineMesageID(16), server GUID(8), HasSecurity(1),
        /// Cookie(4, 如果设置了HasSecurity), public key (如果doSecurity设置为true),
        /// MTU(2). 如果公钥在客户端使用失败，返回ID_PUBLIC_KEY_MISMATCH
        /// </summary>
        ID_OPEN_CONNECTION_REPLY_1,
        /// <summary>
        /// C2S: Header(1), OfflineMesageID(16), Cookie(4, 如果在服务器HasSecurity为true),
        /// clientSupportsSecurity(1 bit), handshakeChallenge (如果在服务器和客户端设置了security),
        /// remoteBindingAddress(6), MTU(2), client GUID(8)
        /// 如果cookie有效则分配连接间隙,服务器没有满，GUID和IP没有使用
        /// </summary>
        ID_OPEN_CONNECTION_REQUEST_2,
        ID_OPEN_CONNECTION_REPLY_2,
        ID_CONNECTION_REQUEST,
        ID_REMOTE_SYSTEM_REQUIRES_PUBLIC_KEY,
        ID_OUR_SYSTEM_REQUIRES_SECURITY,
        ID_PUBLIC_KEY_MISMATCH,
        ID_OUT_OF_BAND_INTERNAL,
        ID_SND_RECEIPT_ACKED,
        ID_SND_RECEIPT_LOSS,
        /// <summary>
        /// 1 通知用户连接成功
        /// 2 RakPeer-在客户端/服务器环境下，我们的连接要求服务器已经接受
        /// **连接请求到来时，RakPeer传输内部状态数据，例如RakNetGUID，在禁止列表中检验这些连接，重连列表。
        /// **和其他的安全措施。如果连接是安全 的，安全连接协议启动，发送额外的数据。一旦成功,通知16或者19
        /// </summary>
        ID_CONNECTION_REQUEST_ACCEPTED,
        /// <summary>
        /// RakPeer-如果连接请求无法完成时，给玩家回复这样一个消息
        /// *****是一条概述性消息，意味着与远端系统没有建立连接。可能的原因包括如下几方面：
        /// 1. IP地址错误
        /// 2. 远端系统没有运行RAkNet，或RakPeerInterface::Startup()在这个系统上没有调用。
        /// 3. 远端系统启动了RakNet，但是RakPeerInterface::SetMaximumIncomingConnection没有调用。
        /// 4. 防火墙阻止了你选择的端口上的UDP数据包。
        /// 5. 远端系统的一个路由器阻塞了进入你选择的端口上的UDP数据包。参考NAT Punchthrough插件解决这个问题。
        /// 6. 在Windows Vista上，网络驱动安全服务器包有事破坏了UDP，不仅仅是RakNet，甚至是DirectPlay。这个服务包应该关闭或者不要安装。
        /// 7. Secure Connections启用了，但是安全检查不正确。
        /// 8. 你的iP地址被RakPeerInterface::AddToBanList()函数禁止了。注意有些插件例如Connection filter，有可选的自动禁止IP地址的功能。
        /// </summary>
        ID_CONNECTION_ATTEMPT_FAILED,
        /// <summary>
        /// RakPeer-向你当前要连接到的系统发送连接请求,已经存在
        /// </summary>
        ID_ALREADY_CONNECTED,
        /// <summary>
        /// RakPeer-远端系统已经成功连接。
        /// </summary>
        ID_NEW_INCOMING_CONNECTION,
        /// <summary>
        /// RakPeer-试图连接的系统不接受新的连接。(未释放连接)
        /// </summary>
        ID_NO_FREE_INCOMING_CONNECTIONS,
        /// <summary>
        /// RakPeer-系统在Packet::systemAddress中指定的已经从服务器断开的。对于客户端，这个
        /// 标识意味着服务器已经关闭
        /// </summary>
        ID_DISCONNECTION_NOTIFICATION,
        /// <summary>
        /// RakPeer-可靠数据包不能传递到Packet::systemAddress指定系统。到该系统连接已经断开
        /// </summary>
        ID_CONNECTION_LOST,
        /// <summary>
        /// RakPeer-被要连接到的系统禁止掉了(服务器维护)
        /// </summary>
        ID_CONNECTION_BANNED,
        /// <summary>
        /// 无效密码
        /// RakPeer-远端系统使用了密码，因为设置密码不正确拒绝了连接请求
        /// </summary>
        ID_INVALID_PASSWORD,
        /// <summary>
        /// 无效协议
        /// [[在 RakNetVersion.h中的RAKNET_PROTOCOL_VERSION与远端系统上的本值不匹配
        /// 这意味这两个系统无法通信
        /// 消息的第二个字节包含了远端系统的RAKNET_PROTOCOL_VERSION值]]
        /// </summary>
        ID_INCOMPATIBLE_PROTOCOL_VERSION,
        ID_IP_RECENTLY_CONNECTED,
        ID_TIMESTAMP,
        ID_UNCONNECTED_PONG,
        ID_ADVERTISE_SYSTEM,
        ID_DOWNLOAD_PROGRESS,
        /// <summary>
        /// 顶号情况处理1
        /// ConnectionGraph2插件-在客户端/服务器环境中,一个客户端已经断开了连接，
        /// 修改Packet::systemAddress以反映这个断开的客户端的systemAddress
        /// </summary>
        ID_REMOTE_DISCONNECTION_NOTIFICATION,
        /// <summary>
        /// 顶号情况处理2
        /// ConnectionGraph2插件-在客户端/服务器环境，客户端被迫断开了连接
        /// 修改Packet::systemAddress来反映这个已经断开连接的客户端的systemAddress
        /// </summary>
        ID_REMOTE_CONNECTION_LOST,
        /// <summary>
        /// ConnectionGraph2 产检: 1-4字节 = count。
        /// 对于 (count items)包含了{SystemAddress, RakNetGUID}
        /// </summary>
        ID_REMOTE_NEW_INCOMING_CONNECTION,
        ID_FILE_LIST_TRANSFER_HEADER,
        ID_FILE_LIST_TRANSFER_FILE,
        ID_FILE_LIST_REFERENCE_PUSH_ACK,
        ID_DDT_DOWNLOAD_REQUEST,
        ID_TRANSPORT_STRING,
        ID_REPLICA_MANAGER_CONSTRUCTION,
        ID_REPLICA_MANAGER_SCOPE_CHANGE,
        ID_REPLICA_MANAGER_SERIALIZE,
        ID_REPLICA_MANAGER_DOWNLOAD_STARTED,
        ID_REPLICA_MANAGER_DOWNLOAD_COMPLETE,
        ID_RAKVOICE_OPEN_CHANNEL_REQUEST,
        ID_RAKVOICE_OPEN_CHANNEL_REPLY,
        ID_RAKVOICE_CLOSE_CHANNEL,
        ID_RAKVOICE_DATA,
        ID_AUTOPATCHER_GET_CHANGELIST_SINCE_DATE,
        ID_AUTOPATCHER_CREATION_LIST,
        ID_AUTOPATCHER_DELETION_LIST,
        ID_AUTOPATCHER_GET_PATCH,
        ID_AUTOPATCHER_PATCH_LIST,
        ID_AUTOPATCHER_REPOSITORY_FATAL_ERROR,
        ID_AUTOPATCHER_CANNOT_DOWNLOAD_ORIGINAL_UNMODIFIED_FILES,
        ID_AUTOPATCHER_FINISHED_INTERNAL,
        ID_AUTOPATCHER_FINISHED,
        ID_AUTOPATCHER_RESTART_APPLICATION,
        ID_NAT_PUNCHTHROUGH_REQUEST,
        ID_NAT_CONNECT_AT_TIME,
        ID_NAT_GET_MOST_RECENT_PORT,
        ID_NAT_CLIENT_READY,
        ID_NAT_TARGET_NOT_CONNECTED,
        ID_NAT_TARGET_UNRESPONSIVE,
        ID_NAT_CONNECTION_TO_TARGET_LOST,
        ID_NAT_ALREADY_IN_PROGRESS,
        ID_NAT_PUNCHTHROUGH_FAILED,
        ID_NAT_PUNCHTHROUGH_SUCCEEDED,
        ID_READY_EVENT_SET,
        ID_READY_EVENT_UNSET,
        ID_READY_EVENT_ALL_SET,
        ID_READY_EVENT_QUERY,
        ID_LOBBY_GENERAL,
        ID_RPC_REMOTE_ERROR,
        ID_RPC_PLUGIN,
        ID_FILE_LIST_REFERENCE_PUSH,
        ID_READY_EVENT_FORCE_ALL_SET,
        ID_ROOMS_EXECUTE_FUNC,
        ID_ROOMS_LOGON_STATUS,
        ID_ROOMS_HANDLE_CHANGE,
        ID_LOBBY2_SEND_MESSAGE,
        ID_LOBBY2_SERVER_ERROR,
        ID_FCM2_NEW_HOST,
        ID_FCM2_REQUEST_FCMGUID,
        ID_FCM2_RESPOND_CONNECTION_COUNT,
        ID_FCM2_INFORM_FCMGUID,
        ID_FCM2_UPDATE_MIN_TOTAL_CONNECTION_COUNT,
        ID_FCM2_VERIFIED_JOIN_START,
        ID_FCM2_VERIFIED_JOIN_CAPABLE,
        ID_FCM2_VERIFIED_JOIN_FAILED,
        ID_FCM2_VERIFIED_JOIN_ACCEPTED,
        ID_FCM2_VERIFIED_JOIN_REJECTED,
        ID_UDP_PROXY_GENERAL,
        ID_SQLite3_EXEC,
        ID_SQLite3_UNKNOWN_DB,
        ID_SQLLITE_LOGGER,
        ID_NAT_TYPE_DETECTION_REQUEST,
        ID_NAT_TYPE_DETECTION_RESULT,
        ID_ROUTER_2_INTERNAL,
        ID_ROUTER_2_FORWARDING_NO_PATH,
        ID_ROUTER_2_FORWARDING_ESTABLISHED,
        ID_ROUTER_2_REROUTED,
        ID_TEAM_BALANCER_INTERNAL,
        ID_TEAM_BALANCER_REQUESTED_TEAM_FULL,
        ID_TEAM_BALANCER_REQUESTED_TEAM_LOCKED,
        ID_TEAM_BALANCER_TEAM_REQUESTED_CANCELLED,
        ID_TEAM_BALANCER_TEAM_ASSIGNED,
        ID_LIGHTSPEED_INTEGRATION,
        ID_XBOX_LOBBY,
        ID_TWO_WAY_AUTHENTICATION_INCOMING_CHALLENGE_SUCCESS,
        ID_TWO_WAY_AUTHENTICATION_OUTGOING_CHALLENGE_SUCCESS,
        ID_TWO_WAY_AUTHENTICATION_INCOMING_CHALLENGE_FAILURE,
        ID_TWO_WAY_AUTHENTICATION_OUTGOING_CHALLENGE_FAILURE,
        ID_TWO_WAY_AUTHENTICATION_OUTGOING_CHALLENGE_TIMEOUT,
        ID_TWO_WAY_AUTHENTICATION_NEGOTIATION,
        ID_CLOUD_POST_REQUEST,
        ID_CLOUD_RELEASE_REQUEST,
        ID_CLOUD_GET_REQUEST,
        ID_CLOUD_GET_RESPONSE,
        ID_CLOUD_UNSUBSCRIBE_REQUEST,
        ID_CLOUD_SERVER_TO_SERVER_COMMAND,
        ID_CLOUD_SUBSCRIPTION_NOTIFICATION,
        ID_LIB_VOICE,
        ID_RELAY_PLUGIN,
        ID_NAT_REQUEST_BOUND_ADDRESSES,
        ID_NAT_RESPOND_BOUND_ADDRESSES,
        ID_FCM2_UPDATE_USER_CONTEXT,
        ID_RESERVED_3,
        ID_RESERVED_4,
        ID_RESERVED_5,
        ID_RESERVED_6,
        ID_RESERVED_7,
        ID_RESERVED_8,
        ID_RESERVED_9,
        /// <summary>
        /// GameServer 消息
        /// </summary>
        ID_USER_PACKET_ENUM,
        /// <summary>
        /// LinkServer 消息
        /// </summary>
        ID_USER_PACKET_ENUM2,
    }

}
